jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: ubuntu-18.04
  steps:
  - checkout: self
  - task: UsePythonVersion@0
    displayName: Use Python 3.6
    inputs:
      versionSpec: 3.6
  - task: Bash@3
    displayName: Install python requirement
    inputs:
      filePath: ZFnew/Setup/install_requirements.sh
      workingDirectory: ZFnew/Setup
  - task: PythonScript@0
    displayName: CI Training Process
    inputs:
      scriptPath: ZFnew/CodesScripts/CI-process.py
      arguments: --dataset_name bddata
      workingDirectory: ZFnew/CodesScripts
...
