jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: ubuntu-18.04
  steps:
  - checkout: self
  - task: UsePythonVersion@0
    displayName: Use Python 3.6
    inputs:
      versionSpec: 3.6
  - task: Bash@3
    displayName: Install Bash Requirement
    inputs:
      filePath: Setup/install_requirements.sh
      workingDirectory: Setup
  - task: PythonScript@0
    displayName: CI Training Process
    inputs:
      scriptPath: CodesScripts/CI-process.py
      arguments: --dataset_name bddata
      workingDirectory: CodesScripts
...
